/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import PropTypes from "prop-types";

export function EzbotModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/ezbot.glb");
  const { actions, names } = useAnimations(animations, group);

  const scale = 0.65;

  useEffect(() => {
    // actions[names[1]].setLoop(THREE.LoopOnce);
    // actions[names[1]].clampWhenFinished = true;

    // actions[names[2]].setLoop(THREE.LoopOnce);
    // actions[names[2]].clampWhenFinished = true;

    actions[names[3]].setLoop(THREE.LoopOnce);
    actions[names[3]].clampWhenFinished = true;

    // actions[names[4]].setLoop(THREE.LoopOnce);
    // actions[names[4]].clampWhenFinished = true;

    // actions[names[0]].play(); // body
    // actions[names[1]].play().reset(); // arm left
    // actions[names[2]].play().reset(); // hand left
    actions[names[3]].play().reset(); // arm right
    // actions[names[4]].play().reset(); // hand right
    actions[names[12]].play().reset(); // eye
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Scene"
        scale={[scale, scale, scale]}
        position={[0, 1.8, 0]}
        rotation={[0, 0, 0]}
      >
        <group name="Ezbot-body" position={[0, 4.602, 0.159]}>
          <mesh
            name="Sphere002"
            castShadow
            receiveShadow
            geometry={nodes.Sphere002.geometry}
            material={materials.White}
          />
          <mesh
            name="Sphere002_1"
            castShadow
            receiveShadow
            geometry={nodes.Sphere002_1.geometry}
            material={materials["Dark Purple"]}
          />
          <group
            name="Ezbot-arm-left"
            position={[1.622, 0.49, 0.061]}
            rotation={[-1.647, 1.155, Math.PI / 2]}
            scale={[1, 1, 0.964]}
          >
            <mesh
              name="Cube002"
              castShadow
              receiveShadow
              geometry={nodes.Cube002.geometry}
              material={materials.White}
            />
            <mesh
              name="Cube002_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube002_1.geometry}
              material={materials["Dark Purple"]}
            />
            <group
              name="Ezbot-hand-left"
              position={[0.008, 0.523, -3.729]}
              rotation={[0.123, 0, 0]}
              scale={[1, 1.001, 0.8]}
            >
              <mesh
                name="Cube003"
                castShadow
                receiveShadow
                geometry={nodes.Cube003.geometry}
                material={materials.White}
              />
              <mesh
                name="Cube003_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube003_1.geometry}
                material={materials["Dark Purple"]}
              />
            </group>
          </group>
          <group
            name="Ezbot-arm-right"
            position={[1.622, 0.49, 0.061]}
            rotation={[-1.647, 1.155, Math.PI / 2]}
            scale={[1, 1, 0.964]}
          >
            <mesh
              name="Cube031"
              castShadow
              receiveShadow
              geometry={nodes.Cube031.geometry}
              material={materials.White}
            />
            <mesh
              name="Cube031_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube031_1.geometry}
              material={materials["Dark Purple"]}
            />
            <group
              name="Ezbot-hand-right"
              position={[0, -1.138, -0.078]}
              rotation={[0.123, 0, 0]}
              scale={[1, 1.001, 0.8]}
            >
              <mesh
                name="Cube032"
                castShadow
                receiveShadow
                geometry={nodes.Cube032.geometry}
                material={materials.White}
              />
              <mesh
                name="Cube032_1"
                castShadow
                receiveShadow
                geometry={nodes.Cube032_1.geometry}
                material={materials["Dark Purple"]}
              />
            </group>
          </group>
          <mesh
            name="Ezbot-body-emission"
            castShadow
            receiveShadow
            geometry={nodes["Ezbot-body-emission"].geometry}
            // material={materials['Dark blue emission']}
          >
            <meshStandardMaterial
              emissive={
                props.isActive
                  ? new THREE.Color(0x1434a4)
                  : new THREE.Color(0xff0000)
              }
              emissiveIntensity={1}
            />
          </mesh>
          <group name="Ezbot-head" position={[0, 2.136, -0.159]}>
            <mesh
              name="Cube001"
              castShadow
              receiveShadow
              geometry={nodes.Cube001.geometry}
              material={materials.White}
            />
            <mesh
              name="Cube001_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube001_1.geometry}
              material={materials["Dark Blue"]}
            />
            <mesh
              name="Ezbot-ear"
              castShadow
              receiveShadow
              geometry={nodes["Ezbot-ear"].geometry}
              material={materials["Dark Blue"]}
              position={[1.332, -0.032, 0.077]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              name="Ezbot-ear-large-left-emission"
              castShadow
              receiveShadow
              geometry={nodes["Ezbot-ear-large-left-emission"].geometry}
              material={materials["Light-blue-emission"]}
              position={[-1.355, -0.032, 0.069]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              name="Ezbot-ear-large-right-emission"
              castShadow
              receiveShadow
              geometry={nodes["Ezbot-ear-large-right-emission"].geometry}
              material={materials["Light-blue-emission"]}
              position={[1.32, -0.032, 0.077]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              name="Ezbot-ear-small-left-emission"
              castShadow
              receiveShadow
              geometry={nodes["Ezbot-ear-small-left-emission"].geometry}
              material={materials["Light-blue-emission"]}
              position={[-1.423, -0.032, 0.06]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              name="Ezbot-ear-small-right-emission"
              castShadow
              receiveShadow
              geometry={nodes["Ezbot-ear-small-right-emission"].geometry}
              material={materials["Light-blue-emission"]}
              position={[1.422, -0.032, 0.06]}
              rotation={[0, 0, -Math.PI / 2]}
            />
            <mesh
              name="Ezbot-eye-emission"
              castShadow
              receiveShadow
              geometry={nodes["Ezbot-eye-emission"].geometry}
              position={[-0.542, -0.075, 1.287]}
              rotation={[Math.PI / 2, 0, 0.135]}
              // material={materials['White Light Emission']}
            >
              <meshStandardMaterial
                emissive={new THREE.Color(0xffffff)}
                emissiveIntensity={1}
              />
            </mesh>
            <mesh
              name="Ezbot-face-emission"
              castShadow
              receiveShadow
              geometry={nodes["Ezbot-face-emission"].geometry}
              position={[0, 0, 0.007]}
              // material={materials['Light-blue-emission']}
            >
              <meshStandardMaterial
                emissive={new THREE.Color(0x00ffff)}
                emissiveIntensity={0.8}
              />
            </mesh>
          </group>
          <mesh
            name="Ezbot-power-switch-emission"
            castShadow
            receiveShadow
            geometry={nodes["Ezbot-power-switch-emission"].geometry}
            position={[0, -0.119, 1.389]}
            rotation={[0.056, 0, 0]}
            // material={materials['Dark blue emission']}
          >
            <meshStandardMaterial
              emissive={
                props.isActive
                  ? new THREE.Color(0x1434a4)
                  : new THREE.Color(0xff0000)
              }
              emissiveIntensity={1}
            />
          </mesh>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/ezbot.glb");

export default EzbotModel;

EzbotModel.propTypes = {
  isActive: PropTypes.bool,
};
