import Skills from "../portfolio/Skills/Skills";
import Clock from "../time/Clock";
import Projects from "../portfolio/Projects/Projects";
import { Color } from "three";
import { handleHoverIndicator } from "../../utils/event-handler";
import PropTypes from "prop-types";
import Contacts from "../portfolio/Contacts/Contacts";
// import GodzillaHPIndicator from "../godzilla/GodzillaHPIndicator";
// import GodzillaHPSubIndicator from "../godzilla/GodzillaHPSubIndicator";
import ShinGodzillaModel from "./ShinGodzillaModel";
// import { delay } from "../../utils/utility";
// import MemoizedProjects from "../portfolio/Projects/MemoizedProjects";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useRef, useEffect, Suspense, useState } from "react";
import {
  useTexture,
  useGLTF,
  useAnimations,
  useVideoTexture,
  meshBounds,
} from "@react-three/drei";
import { isAuthenticated, setAuthenticationUser } from "../../core/auth/auth";

// const ShinGodzillaModel = lazy(() => delay(import("./ShinGodzillaModel")));

function Model(props) {
  const group = useRef();
  const { nodes, animations } = useGLTF("/models/room.glb");
  const { actions, names } = useAnimations(animations, group);

  const [, setDoorClickedTimes] = useState(0);

  const room1Texture = useTexture("./textures/room_1.jpg");
  const room2Texture = useTexture("./textures/room_2.jpg");
  const globeTexture = useTexture("./textures/globe.jpg");
  const figurineRoomTexture = useTexture("./textures/figure_room.jpg");

  // Video
  const leftScreenTexture = useVideoTexture("/textures/video/texture_left.mp4");
  const rightScreenTexture = useVideoTexture(
    "/textures/video/texture_left.mp4",
  );
  const centerScreenTexture = useVideoTexture(
    "/textures/video/texture_left.mp4",
  );

  room1Texture.flipY = false;
  room2Texture.flipY = false;
  globeTexture.flipY = false;
  figurineRoomTexture.flipY = false;
  leftScreenTexture.flipY = false;
  rightScreenTexture.flipY = false;
  centerScreenTexture.flipY = false;

  useEffect(() => {
    actions[names[3]].play();
    actions[names[4]].play();
  }, [actions, names]);

  return (
    <>
      <group ref={group} {...props} dispose={null}>
        <group name="Scene">
          <mesh
            name="Room_1001"
            castShadow
            receiveShadow
            geometry={nodes.Room_1001.geometry}
            position={[0, 0.445, 0]}
          >
            <meshBasicMaterial map={room1Texture} />
          </mesh>
          <mesh
            name="Room_2001"
            castShadow
            receiveShadow
            geometry={nodes.Room_2001.geometry}
            position={[8.296, 4.577, -0.213]}
            rotation={[0, 0, Math.PI / 2]}
          >
            <meshBasicMaterial map={room2Texture} />
          </mesh>
          <mesh
            name="Earth001"
            castShadow
            receiveShadow
            geometry={nodes.Earth001.geometry}
            position={[-4.01, 3.472, -1.965]}
            rotation={[0, 1.355, 0]}
            raycast={meshBounds}
            onPointerEnter={() => {
              // handleHoverIndicator("enter", "animateindicator");
            }}
            onPointerLeave={() => {
              // handleHoverIndicator("leave", "animateindicator");
            }}
          >
            <meshBasicMaterial map={globeTexture} />
          </mesh>
          <mesh
            name="Plane_Earth001"
            castShadow
            receiveShadow
            geometry={nodes.Plane_Earth001.geometry}
            position={[-4.01, 3.669, -0.707]}
            rotation={[1.416, Math.PI / 2, 0]}
          >
            <meshBasicMaterial map={globeTexture} />
          </mesh>
          <mesh
            name="Plane_World001"
            castShadow
            receiveShadow
            geometry={nodes.Plane_World001.geometry}
            position={[-77.542, 8.197, 37.24]}
            rotation={[0.033, -0.003, -0.095]}
          >
            <meshBasicMaterial map={globeTexture} />
          </mesh>
          <mesh
            name="Screen_Left001"
            castShadow
            receiveShadow
            geometry={nodes.Screen_Left001.geometry}
            position={[8.296, 4.577, -0.215]}
            rotation={[0, 0, Math.PI / 2]}
          >
            <meshBasicMaterial map={leftScreenTexture} />
          </mesh>
          <mesh
            name="Screen_Middle001"
            castShadow
            receiveShadow
            geometry={nodes.Screen_Middle001.geometry}
            position={[-0.448, 3.368, 7.295]}
            rotation={[0, 0, Math.PI / 2]}
          >
            <meshBasicMaterial map={centerScreenTexture} />
          </mesh>
          <mesh
            name="Screen_Right001"
            castShadow
            receiveShadow
            geometry={nodes.Screen_Right001.geometry}
            position={[-2.812, 3.368, 6.82]}
            rotation={[0, 0, Math.PI / 2]}
          >
            <meshBasicMaterial map={rightScreenTexture} />
          </mesh>
          <mesh
            name="Whiteboard_Surface001"
            castShadow
            receiveShadow
            geometry={nodes.Whiteboard_Surface001.geometry}
            position={[8.296, 4.577, -0.213]}
            rotation={[0, 0, Math.PI / 2]}
          >
            <meshBasicMaterial map={room2Texture} />
            {!props.state.isTLocked && <Skills />}
          </mesh>
          <mesh
            name="Projector_Screen001"
            castShadow
            receiveShadow
            geometry={nodes.Projector_Screen001.geometry}
            position={[8.296, 4.577, -0.213]}
            rotation={[0, 0, Math.PI / 2]}
            raycast={meshBounds}
            onPointerEnter={() => {
              handleHoverIndicator("enter", "viewindicator");
            }}
            onPointerLeave={() => {
              handleHoverIndicator("leave", "viewindicator");
            }}
            onClick={(event) => {
              event.stopPropagation();
              props.handlePLInteraction("SUNLOCK", {
                // look: event.object.position,
                // look: { x: 8.296, y: 4.577, z: -0.213 },
                look: { x: 8.296, y: 4.577, z: 0 },
                pos: { x: 0, y: 5, z: 0 },
              });
            }}
          >
            <meshBasicMaterial map={room2Texture} />
            {!props.state.isTLocked && (
              <Projects
                handlePLInteraction={props.handlePLInteraction}
                handleModalInteraction={props.handleModalInteraction}
                state={props.state}
              />
            )}
          </mesh>
          <mesh
            name="Clock_Screen001"
            castShadow
            receiveShadow
            geometry={nodes.Clock_Screen001.geometry}
            position={[0, 0.445, 0]}
            raycast={meshBounds}
            onPointerEnter={() => {
              // handleHoverIndicator("enter", "themeindicator");
            }}
            onPointerLeave={() => {
              // handleHoverIndicator("leave", "themeindicator");
            }}
          >
            <meshBasicMaterial map={room1Texture} />
            {!props.state.isTLocked && <Clock />}
          </mesh>
          <mesh
            name="GPU_Light_1001"
            castShadow
            receiveShadow
            geometry={nodes.GPU_Light_1001.geometry}
            position={[8.296, 4.577, -0.213]}
            rotation={[0, 0, Math.PI / 2]}
          >
            {/* <meshBasicMaterial map={room2Texture} /> */}
            <meshStandardMaterial
              emissive={new Color(0xb042ff)}
              emissiveIntensity={2}
            />
          </mesh>
          <mesh
            name="GPU_Light_2_001"
            castShadow
            receiveShadow
            geometry={nodes.GPU_Light_2_001.geometry}
            position={[8.296, 4.577, -0.213]}
            rotation={[0, 0, Math.PI / 2]}
          >
            {/* <meshBasicMaterial map={room2Texture} /> */}
            <meshStandardMaterial
              emissive={new Color(0xb042ff)}
              emissiveIntensity={2}
            />
          </mesh>
          <mesh
            name="Fan_Light_2001"
            castShadow
            receiveShadow
            geometry={nodes.Fan_Light_2001.geometry}
            position={[8.296, 4.577, -0.213]}
            rotation={[0, 0, Math.PI / 2]}
          >
            {/* <meshBasicMaterial map={room2Texture} /> */}
            <meshStandardMaterial
              emissive={new Color(0xb042ff)}
              emissiveIntensity={2}
            />
          </mesh>
          <mesh
            name="Fan_Light_1001"
            castShadow
            receiveShadow
            geometry={nodes.Fan_Light_1001.geometry}
            position={[8.296, 4.577, -0.213]}
            rotation={[0, 0, Math.PI / 2]}
          >
            {/* <meshBasicMaterial map={room2Texture} /> */}
            <meshStandardMaterial
              emissive={new Color(0xb042ff)}
              emissiveIntensity={2}
            />
          </mesh>
          <mesh
            name="Phone_Screen001"
            castShadow
            receiveShadow
            geometry={nodes.Phone_Screen001.geometry}
            position={[0, 0.445, 0]}
            raycast={meshBounds}
            onPointerEnter={() => {
              handleHoverIndicator("enter", "contactindicator");
            }}
            onPointerLeave={() => {
              handleHoverIndicator("leave", "contactindicator");
            }}
            onClick={(event) => {
              event.stopPropagation();
              props.handlePLInteraction("SUNLOCK", {
                look: { x: -4, y: 3.368, z: 7.295 },
                // look: { x: -0.448, y: 3.368, z: 7.295 },
                // pos: { x: 0, y: 5, z: 0 },
                pos: { x: 0, y: 5, z: 1 },
              });
            }}
          >
            <meshBasicMaterial map={room1Texture} />
            {!props.state.isTLocked && (
              <Contacts
                handlePLInteraction={props.handlePLInteraction}
                state={props.state}
              />
            )}
          </mesh>
          <mesh
            name="Door"
            castShadow
            receiveShadow
            geometry={nodes.Door.geometry}
            position={[8.296, 4.577, -0.213]}
            rotation={[0, 0, Math.PI / 2]}
            raycast={meshBounds}
            onPointerEnter={() => {
              // handleHoverIndicator("enter", "figurineEnterIndicator");
            }}
            onPointerLeave={() => {
              // handleHoverIndicator("leave", "figurineEnterIndicator");
            }}
            onClick={(event) => {
              event.stopPropagation();

              setDoorClickedTimes((prev) => {
                const newVal = prev + 1;

                if (newVal > 19 || isAuthenticated()) {
                  if (isAuthenticated()) {
                    props.handleSceneLoaderInteraction("TOGGLE_ACTIVE");
                    props.handlePLInteraction("TLOCK");
                  } else {
                    // props.handlePLInteraction("SUNLOCK");
                    setAuthenticationUser();
                    props.handleSceneLoaderInteraction("TOGGLE_ACTIVE");
                    props.handlePLInteraction("TLOCK");
                  }
                  return 0;
                }
                return newVal;
              });
            }}
          >
            <meshBasicMaterial map={room2Texture} />
          </mesh>
          <mesh
            name="Figurine_Room"
            castShadow
            receiveShadow
            geometry={nodes.Figurine_Room.geometry}
            position={[5.285, 14.123, -15.982]}
          >
            <meshBasicMaterial map={figurineRoomTexture} />
          </mesh>
          <mesh
            name="Figurine_Door"
            castShadow
            receiveShadow
            geometry={nodes.Figurine_Door.geometry}
            position={[0, 12.236, -19.936]}
            raycast={meshBounds}
            onPointerEnter={() => {
              // handleHoverIndicator("enter", "figurineExitIndicator");
            }}
            onPointerLeave={() => {
              // handleHoverIndicator("leave", "figurineExitIndicator");
            }}
            onClick={(event) => {
              event.stopPropagation();
              props.handleSceneLoaderInteraction("TOGGLE_ACTIVE");
              props.handlePLInteraction("TUNLOCK");
            }}
          >
            <meshBasicMaterial map={figurineRoomTexture} />
            {/* <GodzillaHPSubIndicator /> */}
          </mesh>
        </group>
      </group>
      {props.state.isTLocked && (
        <Suspense>
          <ShinGodzillaModel state={props.state} />
        </Suspense>
      )}
    </>
  );
}

useGLTF.preload("/models/room.glb");

Model.propTypes = {
  handlePLInteraction: PropTypes.func,
  handleModalInteraction: PropTypes.func,
  handleSceneLoaderInteraction: PropTypes.func,
  state: PropTypes.object,
};

export default Model;
