import Lighting from "../staging/Lighting";
import PropTypes from "prop-types";
/* 
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useGLTF } from "@react-three/drei";

export default function ShinGodzillaModel(props) {
  const { nodes, materials } = useGLTF("/models/kamakura-san.glb");

  return (
    <>
      {/* <Lighting /> */}
      {props.state.tInnerLight && <Lighting />}
      <group {...props} dispose={null}>
        <group
          position={[4.854, 13.235, -22.128]}
          rotation={[-Math.PI / 2, 0, -2.361]}
        >
          <skinnedMesh
            geometry={nodes.Object_176002.geometry}
            material={materials["ShinGoji_body.001"]}
            skeleton={nodes.Object_176002.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_178002.geometry}
            material={materials["ShinGoji_body.001"]}
            skeleton={nodes.Object_178002.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_180002.geometry}
            material={materials["ShinGoji_body.001"]}
            skeleton={nodes.Object_180002.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_182002.geometry}
            material={materials["ShinGoji_body.001"]}
            skeleton={nodes.Object_182002.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_184002.geometry}
            material={materials["ShinGoji_body.001"]}
            skeleton={nodes.Object_184002.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_185002.geometry}
            material={materials["eyeballs.001"]}
            skeleton={nodes.Object_185002.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Object_187002.geometry}
            material={materials["ShinGoji_body.001"]}
            skeleton={nodes.Object_187002.skeleton}
          />
          <primitive object={nodes._rootJoint} />
        </group>
      </group>
    </>
  );
}

// useGLTF.preload("/models/kamakura-san.glb");

ShinGodzillaModel.propTypes = {
  state: PropTypes.object,
};
